name: Deploy to Render (API)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy via API
        env:
          RENDER_API_KEY: rnd_3h7huqrwexm9RebyR7btTp1xjLbM
          RENDER_SERVICE_ID: srv-d2h38mbuibrs73etap00
        run: |
          if [ -z "${RENDER_API_KEY:-}" ]; then echo "Missing secret: RENDER_API_KEY"; exit 1; fi
          if [ -z "${RENDER_SERVICE_ID:-}" ]; then echo "Missing secret: RENDER_SERVICE_ID"; exit 1; fi

          set -euo pipefail
          API_URL="https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys"

          echo "Calling Render API: ${API_URL}"
          RESP="$(curl -sS -w '\n%{http_code}' -X POST \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            "${API_URL}" \
            -d '{}')"

          BODY="$(echo "$RESP" | head -n -1)"
          CODE="$(echo "$RESP" | tail -n1)"

          echo "HTTP $CODE"
          echo "$BODY"

          if [ "$CODE" -lt 200 ] || [ "$CODE" -ge 300 ]; then
            echo "Render API returned non-2xx"
            exit 1
          fi
